# Generated by Django 4.2.2 on 2023-10-26 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('prov_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('shomare_anbar', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('p_code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('discount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('table', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('desired_time', models.DateTimeField(verbose_name='desired date')),
                ('cost', models.IntegerField(default=0)),
                ('promo_used', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='myanbar.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myanbar.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myanbar.order')),
            ],
        ),
    ]
