# Generated by Django 4.2.2 on 2023-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=200)),
                ('tedad', models.IntegerField(default=0)),
                ('prov_name', models.CharField(max_length=200)),
                ('shomare_anbar', models.IntegerField(choices=[(1, 'Yek'), (2, 'Do'), (3, 'Se')])),
            ],
        ),
        migrations.CreateModel(
            name='Sefaresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('table', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('desired_time', models.DateTimeField(verbose_name='desired date')),
                ('coffee_n', models.IntegerField(default=0)),
                ('tea_n', models.IntegerField(default=0)),
                ('cr_n', models.IntegerField(default=0)),
                ('cake_n', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
